import json

from pathlib import Path

from app.config import HISTORY_DIR

from app.cache.semantic_cache import save_cache


CONVERSATION_DIR = HISTORY_DIR / "conversations"


# =====================================================
# Load All History
# =====================================================

def load_history():

    history = []

    files = sorted(

        CONVERSATION_DIR.glob("*.json")

    )

    for file in files:

        with open(

            file,

            "r",

            encoding="utf-8"

        ) as f:

            history.append(

                json.load(f)

            )

    return history


# =====================================================
# Rebuild Semantic Cache
# =====================================================

def rebuild_cache():

    history = load_history()

    count = 0

    for item in history:

        save_cache(

            email=item["email"],

            response=item["response"]

        )

        count += 1

    print(f"{count} conversations added to Semantic Cache.")


# =====================================================
# Show History
# =====================================================

def show_history():

    history = load_history()

    print()

    print("="*60)

    print("Conversation History")

    print("="*60)

    for item in history:

        print()

        print("Time :", item["timestamp"])

        print("Classification :", item["classification"])

        print("Generated By :", item["generated_by"])

        print("Email :")

        print(item["email"])

        print()

        print("Response :")

        print(item["response"])

        print("-"*60)


# =====================================================
# Test
# =====================================================

if __name__ == "__main__":

    show_history()

    # rebuild_cache()